name: HushTime
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2+10

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_multi_formatter: ^2.13.10
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/fonts/

  fonts:
    - family: AlfaSlabOne
      fonts:
        - asset: assets/fonts/AlfaSlabOne-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/Q.png"
